### ISSUE TITLE
Incorporate Google login functionality

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System_3.0#22]
Require login token to access admin section, and also begin to be able to build the custom views, favorites, etc. associated with user prefs.

**Comment by rabu870** [comment]
This is done. What you'll do is:

set `$using_admin` to `true` before including `verify.php`.

For example:

`$using_admin = true;`
`require_once 'verify.php';`

I don't know what to do when a student tries to go to the admin pages... go to the main page with an alert that they don't have permission, perhaps?
