### ISSUE TITLE
Front page: field trip functionality

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System_3.0#24]
There is currently no mechanism for signing out to field trips on index.html.

**Comment by pscsstudentsam** [comment]
Yee

**Comment by nwarmenh** [comment]
@rabu870, are you suggesting that we only need to do this in the single user interface? Or that you've already got code in that branch that be refactored for the front page? Or are you just splashing attitude around?

**Comment by rabu870** [comment]
Both, I suppose.

**Comment by nwarmenh** [comment]
Closing this as it will be addressed by @rabu870 generating a front page table view from his existing card view code.
